version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: new_test_user
      POSTGRES_PASSWORD: new_test_password
      POSTGRES_DB: task_management_db
    ports:
      - "5432:5432"
